### ISSUE TITLE
Scenario config includes

### ISSUE THREAD

**Issue by mgaliar** [activeshadow/minimega#50]
**Describe your feature**
Allow a scenario config to include/reference another scenario config. 

**Expected behavior**
Most experiments will have some base scenario config. Let's say we then want to run 5 different scenarios that each add something different on top of the base scenario. Each new scenario would be it's own scenario file, but the base part of the scenario config would have to be duplicated under each of the new scenario configs. If changes are made to the base portion of the scenario config, that change currently needs to be made across all other configs. Instead, could new scenario configs reference or include a single base scenario config?

**Comment by activeshadow** [comment]
This sounds promising. After talking with @glattercj, the approach I'd like to take is to add a key like `fromScenario` to the app config that, if set, will point to another scenario the app's config should be pulled from. This way, app ordering can still be maintained.

So, as an example, let's say we have the following scenario in the store:

```
apiVersion: phenix.sandia.gov/v1
kind: Scenario
metadata:
  name: base-scenario
  annotations:
    topology: foobar
spec:
  apps:
    host:
    - name: protonuke
      hosts:
      - hostname: host-00
        metadata:
          args: -ssh 10.0.0.254
```

For a new scenario to include the `protonuke` app from the above scenario in it, the new scenario's config would look like the following:

```
apiVersion: phenix.sandia.gov/v1
kind: Scenario
metadata:
  name: actual-scenario
  annotations:
    topology: foobar
spec:
  apps:
    host:
    - name: protonuke
      fromScenario: base-scenario
    - name: wireguard
      hosts:
      - hostname: host-00
        metadata:
          ...
```

/cc @mgaliar, @dnkcom, @glattercj
